stages:
 - build
 - provision
 - deploy

variables:
 DOCKER_IMAGE_NAME: nathaliapaulon/appdevops:latest
 TF_VAR_docker_image_name: $DOCKER_IMAGE_NAME

build:
 stage: build
 image: docker:latest
 services:
    - docker:dind
 script:
    - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
    - docker build -t $DOCKER_IMAGE_NAME .
    - docker push $DOCKER_IMAGE_NAME

provision:
 stage: provision
 image: hashicorp/terraform:latest
 script:
    - terraform init
    - terraform apply -auto-approve -var="docker_image_name=$DOCKER_IMAGE_NAME"
    - terraform output instance_public_dns > public_dns
    - echo "[webservers]
$(cat public_dns)" > inventory.ini

deploy:
 stage: deploy
 image: williamyeh/ansible:alpine3
 script:
    - ansible-playbook -i inventory.ini deploy_app.yml