stages:
 - provision

variables:
 TF_VAR_aws_access_key: $AWS_ACCESS_KEY_ID
 TF_VAR_aws_secret_key: $AWS_SECRET_ACCESS_KEY
 TF_VAR_ssh_public_key: $SSH_PUBLIC_KEY

provision:
 stage: provision
 image: hashicorp/terraform:light
 script:
    - terraform init
    - terraform apply -auto-approve
    - terraform output instance_public_dns > public_dns
 artifacts:
    paths:
      - public_dns
 only:
    - main