stages:
 - build
 - provision

build:
 stage: build
 image: docker:latest
 services:
    - docker:dind
 script:
    - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
    - docker build -t $DOCKER_IMAGE_NAME .
    - docker push $DOCKER_IMAGE_NAME

provision:
 stage: provision
 image:
    name: hashicorp/terraform:light
    entrypoint: [""]
 script:
    - terraform init
    - terraform apply -auto-approve -var="docker_image_name=$DOCKER_IMAGE_NAME" -var="aws_access_key=$AWS_ACCESS_KEY_ID" -var="aws_secret_key=$AWS_SECRET_ACCESS_KEY" -var="ssh_public_key=$SSH_PUBLIC_KEY"