---
- name: Configurar Docker no Amazon Linux 2023
  hosts: all
  become: yes
  tasks:
    - name: Atualizar pacotes e cache do yum
      ansible.builtin.yum:
        name: '*'
        state: latest

    - name: Instalar o Docker
      ansible.builtin.yum:
        name: docker
        state: present

    - name: Iniciar o serviço Docker
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    - name: Adicionar o usuário ec2-user ao grupo docker
      ansible.builtin.user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Fazer o pull da imagem Docker
      ansible.builtin.command: docker pull nathaliapaulon/appdevops:latest
    
    - name: Criar rede nomeada personalizada
      ansible.builtin.docker_network:
        name: bridge
        state: present
      when: criar_rede | default(true)

    - name: Executar a imagem Docker com mapeamento de portas e especificar a rede
      ansible.builtin.docker_container:
        name: meu_app_devops
        image: nathaliapaulon/appdevops:latest
        state: started
        restart_policy: always
        published_ports:
          - "8000:8000"
        networks:
          - name: bridge

    - name: Verificar se o contêiner está rodando
      ansible.builtin.command: docker ps
      register: docker_ps_output

    - name: Mostrar a saída do comando docker ps
      ansible.builtin.debug:
        var: docker_ps_output.stdout_lines