---
- name: Implantar imagem Docker e executar API
  hosts: apidesafio
  become: yes

  tasks:
    - name: Instalar Docker
      ansible.builtin.package:
        name: docker
        state: present

    - name: Extrair imagem do Docker
      docker_image:
        name: nathaliapaulon/appdevops:latest
        source: pull

    - name: Execute o Docker Container para API
      docker_container:
        name: appdevops_api
        image: nathaliapaulon/appdevops:latest
        state: started
        restart_policy: unless-stopped
        published_ports:
          - "8000:8000"