- hosts: all
  become: yes
  tasks:
  - name: Atualiza os pacotes APT
    apt:
      update_cache: yes

  - name: Instala o Python e o Flask
    apt:
      name:
        - python3-pip
        - python3-flask
      state: present

  - name: Copia o projeto para a instância
    copy:
      src: ./app/
      dest: /app

  - name: Instala as dependências do Python
    pip:
      requirements: /app/requirements.txt