groups:
- name: endpoint_check
  rules:
  - alert: EndpointDown
    expr: probe_success == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Endpoint {{ $labels.instance }} is down"
      description: "The endpoint {{ $labels.instance }} has been down for more than 1 minute."
  - alert: HttpStatusCodeIssue
    expr: probe_http_status_code != 200
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "HTTP status code issue for {{ $labels.instance }}"
      description: "The endpoint {{ $labels.instance }} returned HTTP status code {{ $value }}."

# Alerta para latência elevada da API
  - alert: HighAPILatency
    expr: api_request_duration_seconds{job="your_api_job", quantile="0.9"} > 1.5
    for: 3m
    labels:
      severity: warning
    annotations:
      summary: "Latência elevada na API ({{ $labels.instance }})"
      description: "90% das requisições estão demorando mais de 1.5 segundos para {{ $labels.instance }} nos últimos 3 minutos."