modules:
  http_2xx:
    prober: http
    timeout: 5s
    http:
      valid_status_codes: [200, 201, 202, 203, 204, 205, 206, 207, 208, 226, 401, 405]
      method: GET

  http_2xx/otp:
    prober: http
    timeout: 15m
    http:
      valid_status_codes: []
      method: POST
      headers:
        content-type: application/json
      body: '{"mobile": "1235"}'